name: star_menu
description: StarMenu contexctual pop up menu.
version: 0.0.1
author: Marco Bavagnoli <marcobavagnolidev@gmail.com>
homepage: www.marcobavagnoli.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

