name: star_menu
description: Contextual popup menu with different shapes and multiple ways to fine-tune animation and position. The menu entries can be almost any kind of widgets.
version: 1.0.3
author: Marco Bavagnoli <marcobavagnolidev@gmail.com>
homepage: https://pub.dev/packages/star_menu


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

